
export const ALL_ORDERS_CONNECT: 'ALL_ORDERS_CONNECT' = 'ALL_ORDERS_CONNECT';
export const ALL_ORDERS_DISCONNECT: 'ALL_ORDERS_DISCONNECT' = 'ALL_ORDERS_DISCONNECT';
export const ALL_ORDERS_WS_CONNECTING: 'ALL_ORDERS_WS_CONNECTING' = 'ALL_ORDERS_WS_CONNECTING';
export const ALL_ORDERS_WS_OPEN: 'ALL_ORDERS_WS_OPEN' = 'ALL_ORDERS_WS_OPEN';
export const ALL_ORDERS_WS_CLOSE: 'ALL_ORDERS_WS_CLOSE' = 'ALL_ORDERS_WS_CLOSE';
export const ALL_ORDERS_WS_ERROR: 'ALL_ORDERS_WS_ERROR' = 'ALL_ORDERS_WS_ERROR';
export const ALL_ORDERS_WS_MESSAGE: 'ALL_ORDERS_WS_MESSAGE' = 'ALL_ORDERS_WS_MESSAGE';

export const MY_ORDERS_CONNECT: 'MY_ORDERS_CONNECT' = 'MY_ORDERS_CONNECT';
export const MY_ORDERS_DISCONNECT: 'MY_ORDERS_DISCONNECT' = 'MY_ORDERS_DISCONNECT';
export const MY_ORDERS_WS_CONNECTING: 'MY_ORDERS_WS_CONNECTING' = 'MY_ORDERS_WS_CONNECTING';
export const MY_ORDERS_WS_OPEN: 'MY_ORDERS_WS_OPEN' = 'MY_ORDERS_WS_OPEN';
export const MY_ORDERS_WS_CLOSE: 'MY_ORDERS_WS_CLOSE' = 'MY_ORDERS_WS_CLOSE';
export const MY_ORDERS_WS_ERROR: 'MY_ORDERS_WS_ERROR' = 'MY_ORDERS_WS_ERROR';
export const MY_ORDERS_WS_MESSAGE: 'MY_ORDERS_WS_MESSAGE' = 'MY_ORDERS_WS_MESSAGE';